apiVersion: v1
kind: Secret
metadata:
  name: linkding-secret
type: Opaque
stringData:                      # use stringData, not data — lets you write plaintext
  superuser-password: $uperu$er   # kubectl base64-encodes it for you
