apiVersion: v1
kind: Service
metadata:
  labels:
    app: littlelink
  name: littlelink
  namespace: littlelink
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: littlelink
  type: LoadBalancer
